### ISSUE TITLE
Add IP addresses to the certificate SAN list

### ISSUE THREAD

**Issue by JakeSCahill** [redpanda-data/helm-charts#198]
When the cluster has TLS enabled, you currently need to specify the `--brokers` flag with your `rpk` commands. Otherwise, you get the following error:

```
unable to request metadata: unable to dial: x509: cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs
```

See https://redpandacommunity.slack.com/archives/C01AJDUT88N/p1668179349961769 for more context.

**Comment by joejulian** [comment]
Nodes are considered to be ephemeral in Kubernetes and their IPs are not fixed. If you add or remove nodes from the cluster, this could make a tls certificate invalid. I think we should stick with hostnames, only.

**Comment by joejulian** [comment]
@vuldin I think you have an opinion about this subject.
@RafalKorepta I'd like to hear what you think on this, too.

**Comment by vuldin** [comment]
The only issue I see is that DNS is not controlled by the helm chart, so we would have to rely on the user being able to modify DNS records (or make names resolvable somehow) if we only allow hostnames. And considering that a NodePort service is the default for external access, the helm chart can always discover the relevant node's external IP address via an initContainer prior to the Redpanda container starting up (so that we can correctly set external advertised listeners).

Making external access be available via the node's external IP address puts the helm chart in complete control of this feature. Inserting DNS seems to rely on the user to do things they may not be able to do in order to get external access to work. This is the primary reason why I'm for IP-based external access. If there is another way to do this (for instance use something other than a NodePort service that provides a static IP for each Redpanda node) then I'm all for it. We've discussed LoadBalancer, but I think we've also identified problems with that approach.

**Comment by RafalKorepta** [comment]
> cannot validate certificate for 0.0.0.0 because it doesn't contain any IP SANs

This error comes from the fact how @JakeSCahill used the rpk.
```
kubectl exec -ti redpanda-0 --container redpanda -n redpanda -- rpk topic list --tls-enabled --tls-truststore=/etc/tls/certs/default/ca.crt --tls-cert=/etc/tls/certs/default/tls.crt --tls-key=/etc/tls/certs/default/tls.key
```

This command runs rpk which discovers Redpanda configuration automatically. By default it will try `0.0.0.0` as a broker list. @JakeSCahill used `--brokers=redpanda-0.redpanda.redpanda.svc.cluster.local.:9093` which is internal DNS name for first broker in the Redpanda cluster. 

Current certificate has all kind of internal DNS:
https://github.com/redpanda-data/helm-charts/blob/17e0c2fd64892570088c96e4d0b0ba0c2cc954b5/charts/redpanda/templates/certs.yaml#L16-L27

> Nodes are considered to be ephemeral in Kubernetes and their IPs are not fixed. If you add or remove nodes from the cluster, this could make a tls certificate invalid. I think we should stick with hostnames, only.

I agree that helm will not be able to dynamically change Redpanda configuration in case k8s Node will disappear.

Arguments from @vuldin seems to address only onboarding customers that would like to validate Redpanda with external access. If that's the case, then we could create an exception to include initContainer to configure certificate based on Node external IP (if available), but then we need to document this is not production setup.

My personal believe is that we should explore ways to document how to create Redpanda setup with external access that is tight to stable DNS names. I could come up with few PoCs that could be validated against filed team. 

### Side note

I think (didn't tested it) our helm chart will not allow to create certificate if user would define another issuer reference that will contact public certificate authority like ACME. The internal k8s DNS can not be validated. The same applies to IPs if they are included in SAN list.

**Comment by soudaburger** [comment]
How are we expected to create topics via RPK, then?
1. Should we simply be expected to NOT use redpanda-generated TLS certificates?
2. Can we get a "skip TLS verification" configuration option to avoid this?

```bash
redpanda@redpanda-0:/$ rpk topic create -c cleanup.policy=compact -r 3 -p 20 foo bar --tls-enabled
unable to create topics [foo bar]: unable to dial: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

This is basically blocking me from being able to progress since there doesn't seem to be a way to create topics without manually doing so in the console.  There is no "Topic" CRD resource object which would also make this much easier.  But all of the documentation for redpanda is reliant upon rpk working and this just seems like I'm spinning my wheels.

**Comment by joejulian** [comment]
> How are we expected to create topics via RPK, then?
> 
>     1. Should we simply be expected to NOT use redpanda-generated TLS certificates?
> 
>     2. Can we get a "skip TLS verification" configuration option to avoid this?
> 
> 
> ```shell
> redpanda@redpanda-0:/$ rpk topic create -c cleanup.policy=compact -r 3 -p 20 foo bar --tls-enabled
> unable to create topics [foo bar]: unable to dial: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
> ```
> 
> This is basically blocking me from being able to progress since there doesn't seem to be a way to create topics without manually doing so in the console. There is no "Topic" CRD resource object which would also make this much easier. But all of the documentation for redpanda is reliant upon rpk working and this just seems like I'm spinning my wheels.

To use your example:

```
rpk topic create -c cleanup.policy=compact -r 3 -p 20 foo bar --brokers=redpanda-0.redpanda.redpanda.svc.cluster.local.:9093
```

**Comment by JakeSCahill** [comment]
Related issue: https://github.com/redpanda-data/helm-charts/issues/269

**Comment by joejulian** [comment]
I'm going to close this. The chart has the ability to add a custom certificate and a user can create their own certificate and install it this way, allowing them to use whatever subject alt names they wish.

The helm installation outputs examples for using rpk inside the cluster, answering @soudaburger's question.

We're going to rely on CertManager for handling our certificate automation. Creating our own is not in-scope.
