### ISSUE TITLE
Creating ClusterIssuer from a trusted CA not creating Certificates and other issues

### ISSUE THREAD

**Issue by alejandroEsc** [redpanda-data/helm-charts#303]
This ticket is to capture the work of doing the following:

- Enable the use of a CA and fix broken Certificate creation when referencing a ClusterIssuer including using correct SANS values and removing optional fields that were not required. 
- Fix Certificate secret creation that is referenced and required by the sts
- Fix referencing ca.crt that are no created when using an external CA

**Comment by anggutie-dev** [comment]
@alejandroEsc does this include this error when using a ClusterIssuer (Certificate Manager)?

`The certificate request has failed to complete and will be retried: The CSR PEM requests a commonName that is not present in the list of dnsNames or ipAddresses. If a commonName is set, ACME requires that the value is also present in the list of dnsNames or ipAddresses: "redpanda-default-cert" does not exist in`

**Comment by carlreid** [comment]
I also encountered the `commonName` issue as @anggutie-dev mentioned. That could be an easy (famous last words) fix by simply removing it, since it has in fact been deprecated since 2000.

However I also encounter that;
1) The current [list of `dnsNames`](https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/certs.yaml#L37-L52) includes internal and external domain (if you use it) which causes an issue if you're trying to use ACME, as the internal cluster domain is likely not a public address
2) Use of an external domain defined as [`"*.{{ $values.external.domain }}"`](https://github.com/redpanda-data/helm-charts/blob/main/charts/redpanda/templates/certs.yaml#L51) limits the scope of ACME validation to DNS only.

Possible solution for (1) could be to only output the `$values.external.domain` if it is defined, otherwise output the other DNS names.

Possible solution for (2) could be to add a DNS entry-point for each replica like `- "redpanda-N.{{ $values.external.domain }}"` where "redpanda" would be the deployment name, and "N" the nth replica.

**Comment by alejandroEsc** [comment]
A lot of these issues are addressed here: https://github.com/redpanda-data/helm-charts/pull/289 However, this is paused as there are internal questions that we need to answer and some concern that these solutions may not be compatible with a full solution that encapsulates some of this work.

**Comment by carlreid** [comment]
Ah... cheers @alejandroEsc, I'll follow the related PR for any further updates as well then

**Comment by alejandroEsc** [comment]
Closing this issue, as i believe it has been resolved.
