### ISSUE TITLE
Jobs don't set tolerations or nodeSelector (if set)

### ISSUE THREAD

**Issue by vuldin** [redpanda-data/helm-charts#305]
If a cluster has nodes that have taints and labels applied which limit what can be scheduled on them, then jobs in the helm chart won't run. The easiest solution may be to add the same nodeSelector and tolerations that are on the statefulset if they exist.

I think this is a P0 but want to discuss with the team. I just found this issue, and it is blocking a customer deliverable.

**Comment by alejandroEsc** [comment]
https://github.com/redpanda-data/helm-charts/pull/306

**Comment by doganyazar** [comment]
I have a related problem and came to the repo to create an issue but maybe it is better to mention it here. We are using nodeAffinity on sts and it is not possible to set nodeAffinity on the jobs (post_install_job and post_upgrade_job).It would be nice if the template supported it or at least they could use the same nodeAffinity of the sts so that they do not end up on other nodes.
