### ISSUE TITLE
Provide a way to start a cluster in recovery mode

### ISSUE THREAD

**Issue by mattschumpert** [redpanda-data/helm-charts#795]
### What would you like to be added?

https://github.com/redpanda-data/core-internal/issues/783 introduces recovery mode. This tracks ensuring it can be enabled in k8s environments. 

OperatorV2 deployments should test and document configuring recovery mode.

### Why is this needed?

New 23.3 feature

**Comment by mattschumpert** [comment]
@joejulian  I had created this already and bumped it up.

**Comment by mattschumpert** [comment]
FYI @ztlpn  this was on the radar already. We'll get to it by next week I think.

**Comment by alejandroEsc** [comment]
Assuming this is cluster scoped, and not at the broker level (documentation says you should be able to put specific brokers into recovery mode also) there is nothing for us to do here except document the node property and maybe add documentation on how to roll pods so that mode is respected. c.c. @JakeSCahill

**Comment by mattschumpert** [comment]
@alejandroEsc the target is cluster 'scoped' but its a broker (node ) config  property though, not a 'cluster config property'.

**Comment by alejandroEsc** [comment]
Reopening as we need a bit more logic that we first thought.
