### ISSUE TITLE
HELM: set empty securityContext for OpenShift

### ISSUE THREAD

**Issue by dechants** [redpanda-data/helm-charts#939]
### What happened?

Setting the following in values.yaml

```
podSecurityContext: {}
securityContext: {}
containers:
  securityContext: {}
```

is overriden with defaults:

```
helm install redpanda-console --dry-run --debug \ 
     redpanda/console \
     --namespace namespace \
     -f values.yaml

```

```
    spec:
      serviceAccountName: redpanda-console
      securityContext:
        fsGroup: 99
        runAsUser: 99
```

### What did you expect to happen?

Empty securityContext. Similar helm charts with emtpy security context run fine on OpenShift. Setting the user and group to 99 is not allowed on Openshift.

### How can we reproduce it (as minimally and precisely as possible)?. Please include values file.

see above

### Anything else we need to know?

```
99 is not an allowed group, provider restricted-v2: .containers[0].runAsUser: Invalid value: 99: must be in the ranges: [1005620000, 1005629999]"
```

### Which are the affected charts?

Console

### Chart Version(s)

<details>

```console
$ helm -n <redpanda-release-namespace> list 
NAME                    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
redpanda-console        mesda-dev       1               2023-12-18 15:53:47.974418376 +0100 CET deployed        console-0.7.13  v2.3.8 
```

</details>

### Cloud provider

n/a

**Comment by alejandroEsc** [comment]
I believe this is expected behavior for object mappings, see for example https://stackoverflow.com/questions/73715819/whats-the-meaning-of-the-empty-value-kubernetes-helm-chart-yaml-file 

where an empty `{}` value would just merge with the values defaults and so you will end up with what you are not expecting. I have tried to use the following

podSecurityContext: 
securityContext: 

where these are empty and it seems to work as you desired to see for this situation. There is still a bug where we need to set these values to null so Ill have a fix for this soon.

**Comment by dechants** [comment]
Thank you!
